---
- name: Create IP helpers to domain controllers
  hosts: all
  gather_facts: False
  connection: network_cli

  tasks:
  - name: configure ip helpers on multiple interfaces
    ios_config:
      lines:
      - ip helper-address 10.250.90.200
      - no ip redirects
      - no ip proxy-arp
      parents: '{{ item }}'
    with_items:
    - interface Vlan91
    - interface Vlan92
    - interface Vlan93
    - interface Vlan94
    - interface Vlan95
    - interface Vlan96
    - interface Vlan97
    - interface Vlan98
    - interface Vlan99
   
  - name: configure
    ios_config:
      lines:
      - ip dhcp pool monitoring
      - host 10.250.90.203 255.255.255.0
      - hardware-address 525400aaaa03

  - name: configure
    ios_config:
      lines:
      - ip dhcp pool monitoring1
      - host 10.250.90.204 255.255.255.0
      - client-identifier 0152.5400.aaaa.03 
      
   
  - name: configure
    ios_config:
      lines:
      - ip dhcp pool maas
      - host 10.250.90.205 255.255.255.0
      - client-identifier 0152.5400.aaaa.04 

  - name: save running to startup when modified
    ios_config:
      save_when: modified
