---
- name: Create local traffic objects on a BIG-IP
  hosts: all
  gather_facts: False
  connection: local
  vars:
    validate_certs: no
    username: vagrant
    password: admin

  tasks:
    - name: Add nodes to pool
      bigip_pool_member:
        server: 10.250.90.201
        description: webserver-1
        host: 10.250.90.200
        name: server
        pool: web-servers
        port: 80       
      notify:
        - Save the running configuration to disk
 
  handlers:
    - name: Save the running configuration to disk
      bigip_config:
        save: yes
        provider: "{{ provider }}"
