---
- name: Create local traffic objects on a BIG-IP
  hosts: all
  gather_facts: False
  connection: local
  vars:  
    server: 10.250.90.222

  tasks:
  - name: Create pool
    bigip_pool:
      state: present
      name: my-pool
      description: managed by ansible
      partition: Common
      lb_method: least-connections-member
      slow_ramp_time: 120
      provider:
        server: 10.250.90.222
        validate_certs: no
        user: vagrant
        password: vagrant
    delegate_to: localhost
  

