---
- name: Create local traffic objects on a BIG-IP
  hosts: all
  gather_facts: False
  connection: local
  vars:
    server: 10.250.90.222
    user: vagrant
    password: vagrant
    validate_certs: no

  tasks:
  - name: Create pool
    bigip_pool:

      state: present
      name: my-pool
      partition: Common
      lb_method: least-connection-member
      slow_ramp_time: 120
    delegate_to: localhost
  

