---
- name: Create local traffic objects on a BIG-IP
  hosts: all
  gather_facts: False
  connection: local
  vars:  
    user: vagrant
    password: vagrant
    
    server: 10.250.90.222

  tasks:
  - name: Create pool
    bigip_pool:
      provider:
        server: 10.250.90.222
        validate_certs: no
      state: present
      name: my-pool
      partition: Common
      lb_method: least-connections-member
      slow_ramp_time: 120
    delegate_to: localhost
  

