---
- name: Create local traffic objects on a BIG-IP
  hosts: all
  gather_facts: False
  connection: local
  vars:
    validate_certs: no
    username: vagrant
    password: admin

  tasks:
    - name: Add nodes to pool
      bigip_pool_member:
        pool: my-pool
        partition: Common
        host: 10.250.90.200
        port: 80
        description: web server
        connection_limit: 100
        rate_limit: 50
        ratio: 2
        provider:
          server: 10.250.90.222
          user: vagrant
          password: vagrant
      delegate_to: localhost
        
        
        
      #notify:
     #   - Save the running configuration to disk
 
  handlers:
    - name: Save the running configuration to disk
      bigip_config:
        save: yes
        provider: "{{ provider }}"
