---
- name: Install IIS
  hosts: all
  gather_facts: true
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  
  tasks:
   - win_feature:
       name: "web-server"
       state: present
       restart: yes
       include_sub_features: yes
       include_management_tools: yes
