---
- hosts: all
  gather_facts: no

  tasks:
  - name: update the system
    dnf:
      name: "*"
      state: latest
  - name: Add default tools for kvm
    dnf:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - htop
        - tcpdump
        - nano
        - wireshark
        - vagrant
        - qemu-kvm
        - libvirt-daemon-system
        - libvirt-clients
        - virtinst
        - bridge-utils
        - libguestfs-tools
        - virt-top
        - gcc
        - libvirt-daemon-kvm
        - libvirt-devel 
        - make 
        - rdesktop
        - @Development tools'
        - ruby-devel
        - gcc-c++
        - zlib-devel
        
        
   
        

