---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: update the system
    dnf:
      name: "*"
      state: latest
  - name: Add default tools for kvm
    dnf:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - nagios
        - rsyslog
        - tftp-server
        - smokeping
        - mtr
        
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
        
  - name: Enable service httpd, and not touch the state
    service:
      name: httpd
      enabled: yes
