---
- hosts: all
  gather_facts: no
  validate_certs: no

  tasks:
  - name: Add a list of software on Linode VMs ...
    dnf:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - htop
        - tcpdump
        - nano
        - wireshark
