---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: update the system
    dnf:
      name: "*"
      state: latest
  - name: Add default tools for kvm
    dnf:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - htop
        - tcpdump
        - nano
        - wireshark
        - vagrant
        - qemu-kvm
#        - libvirt-daemon-system
#        - libvirt-clients
#        - virtinst
        - bridge-utils
        - libguestfs-tools
        - virt-top
        - gcc
        - libvirt-daemon-kvm
        - libvirt-devel 
        - make 
        - rdesktop
        - '@Development tools'
        - ruby-devel
        - gcc-c++
        - zlib-devel
        - python3
        
  - name: Start service libvirtd, if not started
    service:
      name: libvirtd
      state: started
        
  - name: Enable service libvirtd, and not touch the state
    service:
      name: libvirtd
      enabled: yes

  - name: replace lines
    lineinfile: 
      path: /etc/libvirt/qemu.conf 
      regexp: '^(.*)#user = "root"(.*)$' 
      line: 'user = "root"'
      backrefs: yes
        
  - name: replace line      
    lineinfile: 
      path: /etc/libvirt/qemu.conf 
      regexp: '^(.*)#group = "root"(.*)$' 
      line: 'group = "root"'
      backrefs: yes
      
