---
- hosts: all
  gather_facts: no
 # ANSIBLE_HOST_KEY_CHECKING: no

  tasks:
  - name: update the system
    dnf:
      name: "*"
      state: latest
  - name: Add default tools for kvm
    dnf:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - htop
        - tcpdump
        - nano
        - wireshark
        - vagrant
