---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: update the system
    dnf:
      name: "*"
      state: latest
  - name: Add default tools for kvm
    dnf:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - nagios
        - rsyslog
        - tftp-server
        - smokeping
        - mtr
        
  - name: Disable SELinux
    ansible.posix.selinux:
      state: disabled
