--- 
- name: Domain controller configuration script
  hosts: all
  gather_facts: true
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    dc_address: 10.250.90.200
    upstream_dns_1: 192.168.0.254
    ntp_servers: "0.us.pool.ntp.org,1.us.pool.ntp.org"
    reverse_dns_zone: "10.250.0.0/16"

  tasks:
  - name: Install AD Services feature
    win_feature:   
      include_management_tools: true
      include_sub_features: true
      name: AD-Domain-Services
      state: present
    register: result

  - name: "Create new forest"
    register: result
    win_domain: 
      dns_domain_name: network4all.local
      safe_mode_password: VerySecretP4ssword!

  - name: "Reboot after creation"
    when: result.reboot_required
    win_reboot: 
      msg: "Server config in progress; rebooting..."

  - name: Set internal DNS server 
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - '127.0.0.1'
    delegate_to: '{{ dc_address }}'
    
  - name: Set upstream DNS server 
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - '{{ upstream_dns_1 }}'
    delegate_to: '{{ dc_address }}'
    
  - name: Stop the time service
    win_service:
      name: w32time
      state: stopped
    delegate_to: '{{ dc_address }}'
    
  - name: Set NTP Servers
    win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ntp_servers}}"'
    delegate_to: '{{ dc_address }}'
     
  - name: Start the time service
    win_service:
      name: w32time
      state: started  
    delegate_to: '{{ dc_address }}'
    
  - name: Disable firewall for Domain, Public and Private profiles
    win_firewall:
      state: disabled
      profiles:
      - Domain
      - Private
      - Public
    tags: disable_firewall
    delegate_to: '{{ dc_address }}'
    
  - name: Create reverse DNS zone
    win_shell: "Add-DnsServerPrimaryZone -NetworkID {{reverse_dns_zone}} -ReplicationScope Forest"
    delegate_to: "{{ dc_address }}"    
    retries: 30
    delay: 60
    register: result           
    until: result is succeeded

    
