--- 
- name: Domain controller configuration script
  hosts: all
  gather_facts: true
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    dc_address: 10.250.90.200
    upstream_dns_1: 192.168.0.254
    ntp_servers: "0.us.pool.ntp.org,1.us.pool.ntp.org"
    reverse_dns_zone: "10.250.0.0/16"
    
  tasks:
  - name: Install software
    win_feature:
      name: "active-directory-certificate-services"
      include_management_tools: true
      include_sub_features: true
      state: present
   
