---
- name: Gather Router Facts
  ios_facts:

- name: Clean Up Reports Directory if it exists
  file:
    path: reports
    state: absent
  delegate_to: localhost
  run_once: yes

- name: Create Reports Directory
  file:
    path: reports
    state: directory
    mode: 0755
  delegate_to: localhost
  run_once: yes

- name: Render Facts as Report
  template:
    src: individual_cisco_router_report.html.j2
    dest: "reports/interim_report_{{ inventory_hostname }}.html"
  delegate_to: localhost

- name: Create Interim Report
  template:
    src: consolidated_ios_report.html.j2
    dest: "reports/Consolidated_Cisco_IOS_Report.html"
  delegate_to: localhost
  run_once: yes

- name: Consolidate Interim Report
  assemble:
    src: reports/
    dest: reports/Consolidated_Cisco_IOS_Report.html
  delegate_to: localhost
  run_once: yes

- name: Generate Remaining Portion of Report
  template:
    src: consolidated_ios_report_last_block.html.j2
    dest: reports/consolidated_ios_report_last_block.html
  delegate_to: localhost
  run_once: yes

- name: Get the List of Interim Reports
  find:
    paths: reports/
    patterns: 'interim_report_*.html'
  register: interim_reports_to_delete
  delegate_to: localhost
  run_once: yes

- name: Clean Up Interim Reports
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ interim_reports_to_delete.files }}"
  delegate_to: localhost
  run_once: yes

- name: Consolidate Final Report
  assemble:
    src: reports/
    dest: reports/Consolidated_Cisco_IOS_Report.html
  delegate_to: localhost
  run_once: yes

- name: Final Clean Up
  file:
    path: reports/consolidated_ios_report_last_block.html
    state: absent
  delegate_to: localhost
  run_once: yes

- name: Send Email with Report
  mail:
    host: smtp.gmail.com
    port: 465
    username: "{{ gmail_account }}"
    password: "{{ gmail_account_password }}"
    to: Anthony Lin <anthony.lin.test@gmail.com>
    subject: "Ansible Report"
    body: "The consolidated report for the Cisco IOS Routers can be found in the attached file"
    attach:
     - reports/Consolidated_Cisco_IOS_Report.html
  delegate_to: localhost
  run_once: yes
